### ISSUE TITLE
how to add code without replaceWith()

### ISSUE THREAD

**Issue by lionelB** [KnisterPeter/tscodeshift#23]
Hello, 
I'm try to figure how can I append code since I don't have code to replace
so I can't use replaceWith method
(I need to add a static prop to a class) 
Is it something do-able ?

**Comment by KnisterPeter** [comment]
Hi,
there should be some api like `insertBefore` and `insertAfter`, but currently there isn't.
Any PR is welcome.

**Comment by timofei-iatsenko** [comment]
Any progress here? May be you can suggest approach how to do so? 

I reviewed how `collection.replaceWith` works, and I'm not clearly understand what's going on there. 
Could you point me to documentation about that (TS.transform)?

**Comment by timofei-iatsenko** [comment]
Well, I managed this. I wrote simple method for inserting a node before target, and now i'm struggling with `ts-emitter`. 

Looks like it was not designed for truly new nodes. It tries to print node using code style of original/previous node, which does not exist for inserted nodes.

I see here a solution similar to what recast uses. Have some default rules, and fallback to them if no previous node exist. 

I also not fully understand the idea used in `ts-emitter` about property "newText" expected on each node.

Let's imagine an example, I want to add new import declaration to a file, import node constructs from many different nodes, and somewhere inside I have `StringLiteral` which have `text` property. 

During emitting via `ts-emitter` it fails on that `StringLiteral` node, because neither `newText` or `sourceCode` is presented.
I found a place in `collection.ts` which intended to create this property on replaced node. But it doesn't consider that node may children. 
I saw workaround proposed here https://github.com/KnisterPeter/tscodeshift/issues/24 but this is kinda a hack.

**Comment by KnisterPeter** [comment]
Hi @thekip,
there are a lot of issues with `ts-emitter` right now. They are based on decisions I made early. Especially the heuristics of how to format new code is quite bad and inserting new nodes will lead to bugs and bad formatting.
I've had not much time lately to contribute to this problem.

**Comment by timofei-iatsenko** [comment]
I'm a fan of original jscodeshift, and I currently have time to contribute to ts port of that project (and I also have quite old project written on TS which requires tools for automatic codemods), so probably we can cooperate and I can update ts-emitter as well

**Comment by KnisterPeter** [comment]
@thekip Sure, contributions are welcome. :+1:
